### ISSUE TITLE
Cannot install newer versions of gems

### ISSUE THREAD

**Issue by daveyeu** [wycats/bundler#41]
Trying to bundle Rails 2.3.4 with:
    gem "rails", "2.3.4"
leaves me with this:
    Could not find gem 'rails (= 2.3.4, runtime)' in any of the sources

Seems like a bug since RubyGems itself has no trouble finding and installing the gem.  I'm also having this problem with gems on github (try bundling bmabey-email_spec, 0.3.1).

**Comment by wycats** [comment]
Unfortunately, we're currently working with a source index that only gets updated once per day for gem resolution. We'll need to add support for pulling more recent gemspecs for the incremental part that isn't part of the large daily index yet.

To verify, can you try again? It should work now.

**Comment by daveyeu** [comment]
Yep, I can successfully bundle 2.3.4 now.  Thanks.  Newer github gems, however, still can't be found.

**Comment by brentd** [comment]
+1 - Tried bundling jnunemaker-mongomapper 0.3.5 and had the same issue. I can install it fine via rubygems.

**Comment by brentd** [comment]
Spoke with tekkub on #github and found that they now update their index with `gem generate_index --update`, which will only generate the "modern" spec index format and not the deflated "Marshal.4.8.Z" that bundler is currently using.

**Comment by brentd** [comment]
Added support for newer rubygems index format in my fork: http://github.com/brentd/bundler/

I'm able to bundle the latest gems from github now.

Pull request sent.

**Comment by carllerche** [comment]
Brentd. I applied your patch. Thanks.
